env:
  browser: true
  es2021: true
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
plugins:
  - jest
parserOptions:
  ecmaVersion: latest
  sourceType: module
  allowImportExportEverywhere: true
rules:
  import/extensions: 0
  no-console: 0
  no-unused-expressions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  no-for-of-loops/no-for-of-loops: 0
